# Generated by Django 3.0.3 on 2020-08-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
