# Generated by Django 3.0.3 on 2020-08-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={},
        ),
        migrations.AlterModelTable(
            name='projects',
            table=None,
        ),
    ]
